// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('PaktorApp', ['ui.router', 'ngAnimate', 'ui.bootstrap', 'ngScrollSpy', 'debug']).config(function($locationProvider) {}).controller('ModalVideoCtrl', function($uibModal) {
    this.open = function() {
      return $uibModal.open({
        templateUrl: 'myModalContent.html',
        controller: 'ModalVideoInstanceCtrl as videoInstance',
        size: 'lg'
      });
    };
  }).controller('ModalVideoInstanceCtrl', function($modalInstance) {
    this.close = function() {
      return $modalInstance.dismiss('cancel');
    };
  }).controller('AnchorScrollCtrl', function($anchorScroll, $location) {
    this.go = function(hash) {
      $location.hash(hash);
      return $anchorScroll();
    };
  }).directive('clickToTop', function() {
    return function(scope, element) {
      return element.on('click', function() {
        return document.body.scrollTop = 0;
      });
    };
  });

}).call(this);

//# sourceMappingURL=app.js.map
