// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('PaktorApp', ['ngAnimate', 'ui.bootstrap']).controller('ModalCtrl', function($uibModal, $rootScope) {
    this.open = function(url, link) {
      $rootScope.url = url;
      $rootScope.link = link;
      return $uibModal.open({
        templateUrl: 'myModalContent.html',
        controller: 'ModalInstanceCtrl as instance',
        size: '500'
      });
    };
  }).controller('ModalInstanceCtrl', function($modalInstance) {
    this.close = function() {
      return $modalInstance.dismiss('cancel');
    };
  });

}).call(this);

//# sourceMappingURL=gss.js.map
