// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('PaktorApp').config(function($stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/home');
    return $stateProvider.state('home', {
      url: '/home',
      templateUrl: 'view/ko/home.html'
    }).state('about', {
      url: '/about',
      templateUrl: 'view/ko/about.html',
      controller: function($scope, $location, $anchorScroll) {
        $scope.showMore = function() {
          if (!$scope.p1) {
            return $scope.p1 = 1;
          } else {
            return $scope.p2 = 1;
          }
        };
        return $scope.go = function(hash) {
          $location.hash(hash);
          return $anchorScroll();
        };
      }
    }).state('blog', {
      url: '/blog',
      templateUrl: 'view/ko/blog.html'
    }).state('gaigai', {
      url: '/gaigai',
      templateUrl: 'view/ko/gaigai.html'
    }).state('career', {
      url: '/career',
      templateUrl: 'view/ko/career.html'
    }).state('contact', {
      url: '/contact',
      templateUrl: 'view/ko/contact.html'
    }).state('web_app', {
      url: '/web_app',
      templateUrl: 'view/ko/web_app.html'
    }).state('term', {
      url: '/term',
      templateUrl: 'view/ko/term.html'
    }).state('privacy', {
      url: '/privacy',
      templateUrl: 'view/ko/privacy.html'
    }).state('faq', {
      url: '/faq',
      templateUrl: 'view/ko/faq.html'
    }).state('download', {
      url: '/download',
      templateUrl: 'view/ko/download.html'
    }).state('stories', {
      url: '/stories',
      templateUrl: 'view/ko/stories.html'
    });
  });

}).call(this);

//# sourceMappingURL=route.ko.js.map
