// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('PaktorApp').config(function($stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise("/about");
    return $stateProvider.state('about', {
      url: '/about',
      templateUrl: '/about.html'
    });
  });

}).call(this);

//# sourceMappingURL=route.js.map
