// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('PaktorApp').config(function($stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/home');
    return $stateProvider.state('home', {
      url: '/home',
      templateUrl: 'view/ms/home.html'
    }).state('about', {
      url: '/about',
      templateUrl: 'view/ms/about.html',
      controller: function($scope, $location, $anchorScroll) {
        $scope.showMore = function() {
          if (!$scope.p1) {
            return $scope.p1 = 1;
          } else {
            return $scope.p2 = 1;
          }
        };
        return $scope.go = function(hash) {
          $location.hash(hash);
          return $anchorScroll();
        };
      }
    }).state('blog', {
      url: '/blog',
      templateUrl: 'view/ms/blog.html'
    }).state('gaigai', {
      url: '/gaigai',
      templateUrl: 'view/ms/gaigai.html'
    }).state('career', {
      url: '/career',
      templateUrl: 'view/ms/career.html'
    }).state('contact', {
      url: '/contact',
      templateUrl: 'view/ms/contact.html'
    }).state('web_app', {
      url: '/web_app',
      templateUrl: 'view/ms/web_app.html'
    }).state('term', {
      url: '/term',
      templateUrl: 'view/ms/term.html'
    }).state('privacy', {
      url: '/privacy',
      templateUrl: 'view/ms/privacy.html'
    }).state('faq', {
      url: '/faq',
      templateUrl: 'view/ms/faq.html'
    }).state('download', {
      url: '/download',
      templateUrl: 'view/ms/download.html'
    });
  });

}).call(this);

//# sourceMappingURL=route.ms.js.map
